CREATE TABLE IF NOT EXISTS `user` (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(256),
  userAccount VARCHAR(256),
  avatarUrl VARCHAR(1024),
  gender INT,
  userPassword VARCHAR(512) NOT NULL,
  phone VARCHAR(128),
  email VARCHAR(512),
  useStatus INT DEFAULT 0 NOT NULL,
  createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  isDelete INT DEFAULT 0 NOT NULL,
  userRole INT DEFAULT 0 NOT NULL,
  planetCode VARCHAR(512)
);

